# Generated by Django 5.2.15 on 2026-07-07 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icone', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('descricao', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('preco_avulso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('eh_gratuito', models.BooleanField(default=False)),
                ('eh_premium', models.BooleanField(default=False)),
                ('arquivo_principal_key', models.CharField(blank=True, default='', help_text='Chave do objeto no R2 (ex: projetos/abc123/modelo.skp)', max_length=500)),
                ('preview_glb_key', models.CharField(blank=True, default='', help_text='Chave do preview 3D .glb no R2', max_length=500)),
                ('thumbnail', models.URLField(blank=True, default='')),
                ('peso_mb', models.FloatField(default=0)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('publicado', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos', to='catalogo.categoria')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ('-criado_em',),
            },
        ),
    ]
