# Generated by Django 5.2.15 on 2026-07-07 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraAvulsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('reembolsado', 'Reembolsado')], default='pendente', max_length=20)),
                ('gateway_id', models.CharField(blank=True, default='', help_text='ID da cobrança no Asaas', max_length=100)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_avulsas', to='catalogo.projeto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_avulsas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra Avulsa',
                'verbose_name_plural': 'Compras Avulsas',
            },
        ),
    ]
